spring.application.name=financedashboardapi
server.port=${PORT:8000}
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/financeapi}
app.jwt.secret=${JWT_SECRET:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855}
app.jwt.expiration-ms=86400000