spring.application.name=financedashboardapi
server.port=8000
# Database
spring.data.mongodb.uri=mongodb://localhost:27017/financeapi

app.jwt.secret=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
